backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "src/utility/data/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "uuid" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Subcategory", name: "subcategory", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Images", name: "images", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Brand", name: "brand", widget: "string" }
      - { label: "Status", name: "status", widget: "select", options: ["Available", "Sold"] }