backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "categories"
    label: "Categorías"
    folder: "src/data/categories"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Nombre", name: "name", widget: "string" }

  - name: "subcategories"
    label: "Subcategorías"
    folder: "src/data/subcategories"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Nombre", name: "name", widget: "string" }
      - { 
          label: "Categoría", 
          name: "category", 
          widget: "relation", 
          collection: "categories", 
          search_fields: ["name"], 
          value_field: "name", 
          display_fields: ["name"] 
        }

  - name: "products"
    label: "Productos"
    folder: "src/data/products"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "ID", name: "id", widget: "uuid", prefix: 'prod' }
      - { label: "Título", name: "title", widget: "string" }
      - { 
          label: "Categorías", 
          name: "category", 
          widget: "relation", 
          collection: "categories", 
          search_fields: ["name"], 
          value_field: "name", 
          display_fields: ["name"] 
        }
      - 
        label: "Subcategorías"
        name: "subcategory"
        widget: "relation"
        collection: "subcategories"
        search_fields: ["name"]
        value_field: "name"
        display_fields: ["name"]
        required: false
      - { label: "Descripción", name: "description", widget: "markdown" } # Rich text content
      - { label: "Contenido", name: "body", widget: "markdown" } # Rich text content
      - 
        label: "Imágenes"
        name: "images"
        widget: "list"
        field: 
          label: "Image"
          name: "image"
          widget: "image"
      - { label: "Precio Viejo", name: "oldPrice", widget: "number" }
      - { label: "Precio Nuevo", name: "newPrice", widget: "number" }
      - { label: "Marca", name: "brand", widget: "string" }
      - { label: "Estado", name: "status", widget: "select", options: ["Disponible", "Agotado", "En Oferta"], default: "Available" }
      - { label: "Fecha Agregado", name: "dateAdded", widget: "datetime", required: true, default: '{{now}}' }

  - name: "groups"
    label: "Grupos"
    folder: "src/data/groups"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Nombre Grupo", name: "name", widget: "string" }
      - 
        label: "Categorías"
        name: "categories"
        widget: "relation"
        collection: "categories"
        search_fields: ["name"]
        value_field: "name"
        display_fields: ["name"]
        multiple: true
      - 
        label: "Ícono"
        name: "icon"
        widget: "select"
        options:
          - { label: "Pie", value: "fi-rs-pie" }
          - { label: "Snowflake (Refrigeration)", value: "fi-rr-snowflake" }
          - { label: "Pan (Kitchen/Cooking)", value: "fi-tr-pan" }
          - { label: "Plate (Meal Preparation)", value: "fi-tr-plate" }
          - { label: "Knife (Butchering)", value: "fi-rr-knife" }
          - { label: "Box (Gondolas)", value: "fi-rr-box" }
          - { label: "Tools (Accessories)", value: "fi-rr-tools" }
          - { label: "Dots (Others)", value: "fi-rr-dots" }
          - { label: "Folder", value: "fi-rr-folder" }
          - { label: "Apps", value: "fi-rr-apps" }
          - { label: "Star", value: "fi-rr-star" }
          - { label: "Alarm Clock", value: "fi-rr-alarm-clock" }
          - { label: "Bell", value: "fi-rr-bell" }
          - { label: "Shopping Cart", value: "fi-rr-shopping-cart" }
          - { label: "Heart", value: "fi-rr-heart" }
          - { label: "Check", value: "fi-rr-check" }

  - name: "blogs"
    label: "Noticias"
    folder: "src/data/blogs"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "ID", name: "id", widget: "uuid", prefix: 'blog' }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "markdown" } # Rich text content
      - { label: "Contenido", name: "body", widget: "markdown" } # Rich text content
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Fecha Agregado", name: "dateAdded", widget: "datetime", required: true, default: '{{now}}' }

  - name: "catalogs"
    label: "Catálogos"
    folder: "src/data/catalogs"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "ID", name: "id", widget: "uuid", prefix: 'catalog' }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" } # Rich text content
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Fecha Agregado", name: "dateAdded", widget: "datetime", required: true, default: '{{now}}' }
      - label: "Archivo PDF"
        name: "pdf_file"
        widget: "file"
        media_library:
          config:
            multiple: true
