backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "categories"
    label: "Categories"
    folder: "src/data/categories"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Category Name", name: "name", widget: "string" }

  - name: "subcategories"
    label: "Subcategories"
    folder: "src/data/subcategories"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Subcategory Name", name: "name", widget: "string" }
      - { 
          label: "Category", 
          name: "category", 
          widget: "relation", 
          collection: "categories", 
          search_fields: ["name"], 
          value_field: "name", 
          display_fields: ["name"] 
        }

  - name: "products"
    label: "Products"
    folder: "src/data/products"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "ID", name: "id", widget: "uuid", prefix: 'prod', required: true }
      - { label: "Title", name: "title", widget: "string" }
      - { 
          label: "Category", 
          name: "category", 
          widget: "relation", 
          collection: "categories", 
          search_fields: ["name"], 
          value_field: "name", 
          display_fields: ["name"] 
        }
      - 
        label: "Subcategory"
        name: "subcategory"
        widget: "relation"
        collection: "subcategories"
        search_fields: ["name"]
        value_field: "name"
        display_fields: ["name"]
        required: false
      - { label: "Description", name: "description", widget: "markdown" } # Rich text content
      - { label: "Body", name: "body", widget: "markdown" } # Rich text content
      - 
        label: "Images"
        name: "images"
        widget: "list"
        field: 
          label: "Image"
          name: "image"
          widget: "image"
      - { label: "Old Price", name: "oldPrice", widget: "number" }
      - { label: "New Price", name: "newPrice", widget: "number" }
      - { label: "Brand", name: "brand", widget: "string" }
      - { label: "Status", name: "status", widget: "select", options: ["Available", "Soldout"], default: "Available" }
      - { label: "Date Added", name: "dateAdded", widget: "datetime", required: true, default: "" }

  - name: "groups"
    label: "Groups"
    folder: "src/data/groups"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Group Name", name: "name", widget: "string" }
      - 
        label: "Categories"
        name: "categories"
        widget: "relation"
        collection: "categories"
        search_fields: ["name"]
        value_field: "name"
        display_fields: ["name"]
        multiple: true
      - 
        label: "Icon"
        name: "icon"
        widget: "select"
        options:
          - { label: "Pie", value: "fi-rs-pie" }
          - { label: "Snowflake (Refrigeration)", value: "fi-rr-snowflake" }
          - { label: "Pan (Kitchen/Cooking)", value: "fi-tr-pan" }
          - { label: "Plate (Meal Preparation)", value: "fi-tr-plate" }
          - { label: "Knife (Butchering)", value: "fi-rr-knife" }
          - { label: "Box (Gondolas)", value: "fi-rr-box" }
          - { label: "Tools (Accessories)", value: "fi-rr-tools" }
          - { label: "Dots (Others)", value: "fi-rr-dots" }
          - { label: "Folder", value: "fi-rr-folder" }
          - { label: "Apps", value: "fi-rr-apps" }
          - { label: "Star", value: "fi-rr-star" }
          - { label: "Alarm Clock", value: "fi-rr-alarm-clock" }
          - { label: "Bell", value: "fi-rr-bell" }
          - { label: "Shopping Cart", value: "fi-rr-shopping-cart" }
          - { label: "Heart", value: "fi-rr-heart" }
          - { label: "Check", value: "fi-rr-check" }